#!/usr/bin/python3

import json
import subprocess

"""
This little script is used by the xendomains init script. It prints all running
domUs with their domain id and name.
"""

cmd = ('xen', 'list', '-l')
xen_list_json = subprocess.check_output(cmd)
for domU_info in json.loads(xen_list_json):
    domid = domU_info['domid']
    if domid == 0:
        continue
    name = domU_info['config']['c_info']['name']
    print(domid, name)
